name: juspayglobalsdkflutter
description: >-
  Flutter plugin for JuspayglobalPaymentSDK which enables payment orchestration via different dynamic modules.
version: 4.0.20
repository: https://github.com/juspay/tenant-sdk-flutter
homepage: https://juspay.in/

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.juspay.hyper_sdk_flutter
        pluginClass: JuspayglobalSdkFlutterPlugin
      ios:
        pluginClass: JuspayglobalSdkFlutterPlugin
